### ISSUE TITLE
Paper ideas - Winter 2024/25

### ISSUE THREAD

**Issue by tpetricek** [prgprg-org/reading-group#1]
Send your paper ideas here. 

* Please post one paper per issue! 

* Please make it clear if you are willing to read the paper and lead the discussion about it, or if you are merely interested in the paper, but would prefer someone else to discuss it.

* Use 👍 reaction to vote for papers you would like to read at the reading group. Use ❤️ if you like the paper so much you want to present it. We can also add 🚀 for scheduled papers.

**Comment by tpetricek** [comment]
Ideas from M. sent by email:

* Paul Downen, Zachary Sullivan, Zena M. Ariola & Simon Peyton Jones. [Codata in Action](https://link.springer.com/chapter/10.1007/978-3-030-17184-1_5)
* David Binder, Marco Tzschentke, Marius Müller, Klaus Ostermann. [Grokking the Sequent Calculus](https://dl.acm.org/doi/10.1145/3674639)

From Pierre back in June:

* Milod Kazerounian, Sankha Narayan Guria, Niki Vazou, Jeffrey S. Foster, David Van Horn. [Type-Level Computations for Ruby Libraries](https://arxiv.org/abs/1904.03521)
* Alternatively other papers from Jeffrey Foster's group such as (but Tomas liked the above the best!)
  - Just-in-Time Static Type Checking for Dynamic Languages
  - SimTyper: Sound Type Inference for Ruby using Type Equality Prediction
  - The Ruby Type Checker
  - Static Typing for Ruby on Rails
  - Dynamic Inference of Static Types for Ruby

**Comment by tpetricek** [comment]
I have this paper on my reading list:

* Clemens Nylandsted Klokmose, James R. Eagan, Peter van Hardenberg. [MyWebstrates: Webstrates as Local-first Software](https://cs.au.dk/~clemens/files/MyWebstrates-UIST2024.pdf)

**Comment by tpetricek** [comment]
Ideas from M. sent by email:

* David Binder, Marco Tzschentke, Marius Müller, Klaus Ostermann. [Grokking the Sequent Calculus](https://dl.acm.org/doi/10.1145/3674639)

**Comment by fikovnik** [comment]
Digging more into types:

[A Calculus for Overloaded Functions with Subtyping](https://dl.acm.org/doi/10.1145/141478.141537)

Authors: [Giuseppe Castagna](https://dl.acm.org/doi/10.1145/141478.141537#), [Giorgio Ghelli](https://dl.acm.org/doi/10.1145/141478.141537#), [Giuseppe Longo](https://dl.acm.org/doi/10.1145/141478.141537#)

[ACM SIGPLAN Lisp Pointers, Volume V, Issue 1](https://dl.acm.org/toc/sigplan-lisppointers/1992/V/1)

**Comment by fikovnik** [comment]
I hope I converted all into the issue paper per issue.
Please update your votes.
